In [2]:
import numpy as np
import pandas as pd


In [37]:
#1 How likely is it that you roll doubles when rolling two dice?

n_simulations = nrows = 10**5
n_dice_rolled = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

df = pd.DataFrame(rolls)
df.head(5)

0  1
0  3  2
1  4  5
2  2  4
3  1  1
4  5  1

In [38]:
roll_doubles = (df[0] == df[1]).mean()
roll_doubles

0.16483

In [48]:
# Exercise 1 Alternate Solution 
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)

first_die, second_die

(array([3, 4, 3, ..., 5, 3, 6]), array([6, 2, 1, ..., 2, 3, 3]))

In [47]:
(first_die == second_die).mean()

0.16606

In [54]:
#2 If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

simulation = np.random.choice(["heads", "tails"], 100_000 * 8, p = [.5,.5]).reshape(100_000, 8)
df = pd.DataFrame(simulation)
df1 = (df=="heads")

# the probability of exactly three heads
(df1.sum(axis = 1) == 3).mean() 


0.21698

In [64]:
# probability of more than three heads
(df1.sum(axis =1) > 3).mean() 

0.63804

In [65]:
#2 Alternate Solution 
outcomes = ['heads', 'tails']
n_simulations = 100_000
n_trials = 8 #b/c 8 coins
flips = np.random.choice(outcomes, size=(n_simulations, n_trials))
(flips == 'heads')

array([[False,  True, False, ...,  True,  True,  True],
       [False, False,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True, False, False],
       ...,
       [False, False, False, ..., False,  True,  True],
       [False, False, False, ..., False,  True,  True],
       [False,  True,  True, ...,  True, False,  True]])

In [67]:
sum_of_flips = (flips == 'heads').sum(axis=1)
sum_of_flips

array([4, 4, 5, ..., 2, 3, 6])

In [68]:
(sum_of_flips == 3).mean()

0.21808

In [69]:
(sum_of_flips > 3).mean()

0.63819

In [56]:
#3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

billboard = np.random.choice(['webdevelopment', 'datascience'], size = (100_000,2), p =(0.75, 0.25)).reshape(100_000, 2)
datascience_billboard = billboard ==['datascience', 'datascience']
(datascience_billboard.sum(axis =1)==2).mean()

0.06194

In [70]:
# 3 Alternate Solution
outcomes = ['webdev', 'ds']
drivebys = np.random.choice(outcomes, size = (100_000, 2), p = [0.75, 0.25])
(drivebys == 'ds')

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False,  True],
       [False,  True]])

In [75]:
sum_of_drivebys = (drivebys == 'ds').sum(axis=1)
sum_of_drivebys

array([0, 0, 0, ..., 0, 1, 1])

In [76]:
(sum_of_drivebys == 2).mean()

0.062

In [83]:
#4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

poptarts = np.random.normal(3, 1.5, size = (100_000, 5)) 
# 5 because of 5 days between Mon-Fri
# 3 poptart packages is specified mean, 1.5 is std dev
poptarts


array([[2.98992299, 1.56375789, 5.16384864, 3.30251713, 3.81988848],
       [2.76384356, 1.79697976, 1.90386386, 1.61480224, 2.20077029],
       [4.32037113, 6.60857019, 3.00961195, 3.26314202, 2.21187184],
       ...,
       [2.12887583, 3.03929328, 1.68101368, 2.75227849, 1.14428215],
       [2.60049799, 3.59137457, 3.68761694, 4.05050287, 1.19782085],
       [5.88254944, 2.6856739 , 3.82881028, 3.79317684, 2.78082093]])

In [85]:
weekly_demand = poptarts.sum(axis=1)
weekly_demand

array([16.83993514, 10.28025971, 19.41356712, ..., 10.74574343,
       15.12781322, 18.9710314 ])

In [118]:
(weekly_demand <= 17). mean() 

0.72597

In [115]:
#4 Class Solution

pop_avg = 3
pop_std = 1.5
n_trials = n_nols = 5
n_simulations = n_rows = 1_000_000
simulated_consumed_poptarts = np.random.normal(pop_avg, pop_std, size =(n_simulations, n_trials))
simulated_consumed_poptarts

array([[3.0090451 , 3.03046485, 4.81249209, 3.21069401, 1.88327606],
       [3.32365401, 1.16377461, 4.01697993, 3.40104115, 6.87566303],
       [3.53086164, 2.2182025 , 2.0495082 , 2.63896644, 0.97494356],
       ...,
       [4.35074793, 0.18729575, 3.89433026, 4.11097154, 1.95753614],
       [2.17922115, 4.93493686, 2.12381904, 5.03740718, 0.88688132],
       [3.93773228, 4.15014638, 4.82513892, 4.30188352, 2.03217866]])

In [117]:
calculated_prob = (simulated_consumed_poptarts.sum(axis = 1) <= 17).mean()
calculated_prob

0.724221

In [87]:
#5 Compare Heights
    # Men have an average height of 178 cm and standard deviation of 8cm.
    # Women have a mean of 170, sd = 6cm.
    # If a man and woman are chosen at random, P(woman taller than man)?

men = np.random.normal(178, 8, size=(100_00))
men


array([169.00548952, 168.17205702, 181.52430776, ..., 182.4247252 ,
       178.97743371, 181.15386036])

In [88]:
women = np.random.normal(170, 6, size=(100_00))
women

array([169.76310827, 171.60588145, 169.52987959, ..., 179.35309141,
       167.04862785, 172.41585743])

In [89]:
(women>men).mean()

0.2034

In [120]:
#5 Class Solution
men_avg = 178
men_std = 8
wmn_avg = 170
wmn_std = 6

In [121]:
s_men = np.random.normal(men_avg, men_std, 1_000_000)
s_men

array([164.76646582, 174.07314598, 182.96271275, ..., 180.73774697,
       177.54073614, 179.47074437])

In [122]:
s_wmn = np.random.normal(wmn_avg, wmn_std, 1_000_000)
s_wmn

array([165.17517522, 179.13392751, 179.18441179, ..., 177.31155761,
       166.03699215, 175.86000635])

In [123]:
(s_wmn > s_men).mean()

0.211617

In [166]:
#6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
    #What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
    # What is the probability that we observe an installation issue within the first 150 students that download anaconda?
    # How likely is it that 450 students all download anaconda without an issue?

#probability of 50 successes    
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 50), p = (1/250, 249/250))

In [167]:
success_50 = ((anaconda_install == 'success').sum(axis=1) == 50).mean()
success_50

0.8179

In [168]:
#probabilty of 100 successes
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 100), p = (1/250, 249/250))


success_100 = ((anaconda_install == 'success').sum(axis=1) == 100).mean()
success_100

0.66806

In [182]:
#6b What is the probability that we observe an installation issue within the first 150 students that download anaconda?

anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 150), p = (1/250, 249/250))

install_issue = ((anaconda_install == 'success').sum(axis=1) < 150).mean()
install_issue

0.45313

In [185]:
#6b Alternate Solution 
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 150), p = (1/250, 249/250))

install_issue = ((anaconda_install == 'fail').sum(axis=1) > 0).mean()
install_issue

0.45205

In [183]:
#6c How likely is it that 450 students all download anaconda without an issue?
anaconda_install = np.random.choice(['fail', 'success'], size = (100_000, 450), p = (1/250, 249/250))
success_450 = ((anaconda_install == 'success').sum(axis=1) == 450).mean()
success_450


0.16503

In [9]:
#7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
    # How likely is it that a food truck will show up sometime this week?

In [186]:
#7 Class Solution
# You haven't seen a food truck there in 3 days. How unlikely is this?
n_simulations = nrows = 1_000_000
n_trials = ncols = 3
food_truck = 1
no_truck = 0
lunch_days = np.random.choice([food_truck, no_truck], size=(n_simulations, n_trials), p=[.7, .3])


In [187]:
calculated_prob = (lunch_days.sum(axis=1) == 0).mean()
calculated_prob

0.027211

In [188]:
# How likely is it that a food truck will show up sometime this week?
n_simulations = nrows = 1_000_000
n_trials = ncols = 2
food_truck = 1
no_truck = 0
lunch_days = np.random.choice([food_truck, no_truck], size=(n_simulations, n_trials), p=[.7, .3])

In [189]:
calculated_prob = (lunch_days.sum(axis=1) > 0).mean()
calculated_prob

0.910024

In [207]:
#7 My Solution 
# You haven't seen a food truck there in 3 days. How unlikely is this?

lunch_days = np.random.choice(['food_truck', 'no_truck'], size = (100_000,3), p = ([0.7, 0.3]))
((lunch_days == 'no_truck').sum(axis = 1) == 3).mean()

0.02694

In [214]:
# How likely is it that a food truck will show up sometime this week?

lunch_days = np.random.choice(['food_truck', 'no_truck'], size = (100_000, 7), p = ([0.7, 0.3]))
((lunch_days == 'food_truck').sum(axis = 1) > 0).mean()

0.99984

In [224]:
#8 If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?
bday = np.random.randint(1, 366, (10_000, 23))
(pd.DataFrame(bday).nunique(axis=1) < 23).mean()

0.5071

In [227]:
# What if it's 20 people?
bday = np.random.randint(1, 366, (10_000, 20))
(pd.DataFrame(bday).nunique(axis=1) < 20).mean()

0.4014

In [228]:
# What if it's 40 people?
bday = np.random.randint(1, 366, (10_000, 40))
(pd.DataFrame(bday).nunique(axis=1) < 40).mean()

0.8863